# Guide to TensorFlow Tensors




<a href='https://www.machinelearningnuggets.com/decision-trees-and-random-forests/'><img src='https://drive.google.com/uc?export=view&id=1U9BYq32ayJj5OTr6nEMpelmNcW_xSiAu'>

In [91]:
import tensorflow as tf
print(tf.__version__) # check version


2.14.0


## Various ways of Creating Tensors

* `tf.constant()`
* `tf.variable()`

### `tf.constant()`

It's TensorFlow's most basic method for creating tensors.
This function is vital as it allows us to create tensors with constant values.

Rank 0 tensor(scalar)

In [92]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [93]:
print(f"rank_0_tensor has {rank_0_tensor.ndim} dimensions")

rank_0_tensor has 0 dimensions


Rank 1 tensor(vector)

In [94]:
rank_1_tensor = tf.constant([20, 100])
print(rank_1_tensor)
print(f"\nTensor rank: {tf.rank(rank_1_tensor)}")
print(f"rank_1_tensor has {rank_1_tensor.ndim} dimension")

tf.Tensor([ 20 100], shape=(2,), dtype=int32)

Tensor rank: 1
rank_1_tensor has 1 dimension


Rank 2 tensor - a list of lists

![image.png]()

In [95]:
rank_2_tensor = tf.constant([[20, 10],
                             [15, 30],
                             [45, 35]])
print(rank_2_tensor)
print(f"\nTensor rank: {tf.rank(rank_2_tensor)}")
print(f"rank_2_tensor has {rank_2_tensor.ndim} dimensions")

tf.Tensor(
[[20 10]
 [15 30]
 [45 35]], shape=(3, 2), dtype=int32)

Tensor rank: 2
rank_2_tensor has 2 dimensions


Rank 3 tensor - n-dimensional


In [96]:
rank_3_tensor = tf.constant([
  [[0, 1, 2],
   [3, 4, 5]],
  [[6, 7, 8],
   [9, 10, 11]],
  [[12, 13, 14],
   [15, 16, 17]],])

print(rank_3_tensor)
print(f"\nTensor rank: {tf.rank(rank_3_tensor)}")
print(f"rank_3_tensor has {rank_3_tensor.ndim} dimensions")

tf.Tensor(
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]], shape=(3, 2, 3), dtype=int32)

Tensor rank: 3
rank_3_tensor has 3 dimensions


#### Shape of a Tensor

In [97]:
# retrieve the shape of a tensor
print(f"Rank 0 tensor shape: {tf.shape(rank_0_tensor)}")
print(f"Rank 1 tensor shape: {tf.shape(rank_1_tensor)}")
print(f"Rank 2 tensor shape: {tf.shape(rank_2_tensor)}")
print(f"Rank 3 tensor shape: {tf.shape(rank_3_tensor)}")


Rank 0 tensor shape: []
Rank 1 tensor shape: [2]
Rank 2 tensor shape: [3 2]
Rank 3 tensor shape: [3 2 3]


`Tensor.shape` to check the shape. Does not return a Tensor

In [98]:
print(rank_2_tensor.shape)

(3, 2)


#### Data tyep(`dtype`) of a tensor

A tensor can have any dtype(data type) listed on [`tf. dtypes`](https://www.tensorflow.org/api_docs/python/tf/dtypes). However remember, a tensor must have a specific data type, and all elements within that tensor must conform to that data type. Therefore, a single tensor cannot have two different data types.

For instance,  we cannot create a tensor with both integer and floating-point elements. If you need to work with different data types, you would typically create separate tensors for each type.

We can specify the tensor `dtype` while creating it:

In [99]:
# Float tensor
float32_tensor = tf.constant([20.5, 30.0, 4.3], dtype='float32')
# Integer tensor
int64_tensor = tf.constant([[1, 2, 3], [4, 5, 6]], dtype='int64')
# String tensor
string_tensor = tf.constant(["TensorFlow", "tensors", "dtypes"])

print(float32_tensor)
print(int64_tensor)
print(string_tensor)

tf.Tensor([20.5 30.   4.3], shape=(3,), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)
tf.Tensor([b'TensorFlow' b'tensors' b'dtypes'], shape=(3,), dtype=string)


#### Convert tensors to different datatypes with `tf.cast` function

In [100]:
float32_tensor_as_int32_tensor = tf.cast(float32_tensor, dtype='int32')
int64_tensor_as_float16_tensor = tf.cast(int64_tensor, dtype='float16')
print(float32_tensor_as_int32_tensor)
print(int64_tensor_as_float16_tensor)

tf.Tensor([20 30  4], shape=(3,), dtype=int32)
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float16)


### Creating(or initializing) tensors with specific values(`tf.zeros` and `tf.ones`)

`tf.zeros` and `tf.ones` are commonly used in deep learning(especially when building neural network models) to initialize certain tensors to specific values. By default, a tensor initialized with `tf.zeros` will contain only zeros, while that initialized with `tf.ones` will have only ones.

In [101]:
# Intiailize tensors with ones
ones_tensor1 = tf.ones(shape=(2), dtype='float32') # rank 1 tensor of ones
ones_tensor2 = tf.ones(shape=[2, 3], dtype='int32') # rank 2 tensor of ones

tensor_1d = tf.constant(value = [1, 2])
ones_tensor3 = tf.ones(shape=tensor_1d) # # takes shape as the value of the 1d tensor
print(ones_tensor1)
print(ones_tensor2)
print(ones_tensor3)

tf.Tensor([1. 1.], shape=(2,), dtype=float32)
tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)
tf.Tensor([[1. 1.]], shape=(1, 2), dtype=float32)


In [102]:
# Intiailize tensors with zeors
zeros_tensor1 = tf.zeros(shape=(3), dtype='float32') # rank 1 tensor of zeros
zeros_tensor2 = tf.zeros(shape=[2, 3, 3], dtype='int32') # rank 3 tensor of zeros

tensor_1d = tf.constant(value = [3, 2])
zeros_tensor3 = tf.zeros(shape=tensor_1d) # takes shape as the value of the 1d tensor
print(zeros_tensor1)
print(zeros_tensor2)
print(zeros_tensor3) # 3rows and two columns

tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor(
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]], shape=(2, 3, 3), dtype=int32)
tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


### Example use case of initializing model weight and biases with `tf.zeros`

In [103]:
import tensorflow as tf
import numpy as np

# Generate some dummy data for training
np.random.seed(42)
x_train = np.random.random((100, 10))  # 100 samples with 10 features each
y_train = np.random.randint(2, size=(100,))  # Integer labels

# Define the model
class SimpleModel(tf.keras.Model):
    def __init__(self, input_size, hidden_size, output_size):
        super(SimpleModel, self).__init__()

        # Initialize weights and biases with tf.zeros
        self.weights_hidden = tf.Variable(
            tf.zeros(shape=(input_size,
                            hidden_size)))
        self.biases_hidden = tf.Variable(
            tf.zeros(shape=(hidden_size,)))

        self.weights_output = tf.Variable(
            tf.zeros(shape=(hidden_size,
                            output_size)))
        self.biases_output = tf.Variable(
            tf.zeros(shape=(output_size,)))

    def call(self, inputs):
        # Forward pass
        hidden_layer = tf.matmul(inputs,
                                 self.weights_hidden) + self.biases_hidden
        output_layer = tf.matmul(hidden_layer,
                                 self.weights_output) + self.biases_output
        return output_layer

# Instantiate the model
input_size = 10
hidden_size = 5
output_size = 2
model_zeros = SimpleModel(input_size, hidden_size, output_size)

# Compile the model
model_zeros.compile(optimizer='adam',
                    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                    metrics=['accuracy'])

# Train the model
model_zeros.fit(x_train, y_train, epochs=10, batch_size=32)

# Evaluate the model
loss, accuracy = model_zeros.evaluate(x_train, y_train)
print(f"Final Training Loss: {loss:.4f}, Accuracy: {accuracy:.4f}")


Epoch 1/10
4/4 [==============================] - 1s 8ms/step - loss: 0.6932 - accuracy: 0.5200
Epoch 2/10
4/4 [==============================] - 0s 5ms/step - loss: 0.6931 - accuracy: 0.5200
Epoch 3/10
4/4 [==============================] - 0s 5ms/step - loss: 0.6931 - accuracy: 0.5200
Epoch 4/10
4/4 [==============================] - 0s 4ms/step - loss: 0.6931 - accuracy: 0.5200
Epoch 5/10
4/4 [==============================] - 0s 5ms/step - loss: 0.6931 - accuracy: 0.5200
Epoch 6/10
4/4 [==============================] - 0s 4ms/step - loss: 0.6931 - accuracy: 0.5200
Epoch 7/10
4/4 [==============================] - 0s 5ms/step - loss: 0.6931 - accuracy: 0.5200
Epoch 8/10
4/4 [==============================] - 0s 5ms/step - loss: 0.6931 - accuracy: 0.5200
Epoch 9/10
4/4 [==============================] - 0s 4ms/step - loss: 0.6932 - accuracy: 0.5200
Epoch 10/10
4/4 [==============================] - 0s 4ms/step - loss: 0.6930 - accuracy: 0.5200
Final Training Loss: 0.6930, Accuracy: 

### Creating variable(Changeable) tensors with `tf.variable()`

So far, we have explored how to create tensors with `tf.constant` function. However, we mentioned that tensors created that way are immutable - that is, we can not modify their elements. To prove this point, let's see some examples below:

In [104]:
# tensor with tf.constant()
immutable_tensor = tf.constant([20, 30, 40]) # vector
print(immutable_tensor)

tf.Tensor([20 30 40], shape=(3,), dtype=int32)


In [105]:
# try to change the first element

try:
  immutable_tensor[0] = 100 # index first element and assign new value
  print(immutable_tensor) # item assignment not supported TypeError!
except TypeError:
  print('TypeError: Object does not support item assignment')

TypeError: Object does not support item assignment


We can not modify elements of a `tf.constant` tensor once created. That could be a challenge when creating models like neural networks where trainable parameters like weights and biases must be adjustable during the training process(optimization process). That's where TensorFlow variables come in handy!

TensorFlow variables - mutable tensors, are recommended to represent shared, persistent states your program manipulates(as defined here). They are created using tf.Variable class. The class has some of the following use cases when building machine learning models:

In [106]:
example_variable = tf.Variable([[1.0, 2.0], [3.0, 4.0]])
print(example_variable)
print(f"\nShape: {tf.shape(example_variable)}")
print(f"Rank: {tf.rank(example_variable)}")

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

Shape: [2 2]
Rank: 2


Variables can hold any type, just like tensors:

In [107]:
bool_variable = tf.Variable([False, True, True, False, False])
int32_variable = tf.Variable([20, 40, 15], dtype='int32')

print(bool_variable)
print(int32_variable)

<tf.Variable 'Variable:0' shape=(5,) dtype=bool, numpy=array([False,  True,  True, False, False])>
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([20, 40, 15], dtype=int32)>


#### Modifying the variable with `assign`

In [108]:
int32_variable = tf.Variable([20, 40, 15], dtype='int32')
print(f"Old variable: {int32_variable.numpy()}")
# modify the variable elements
int32_variable = int32_variable.assign([12, 15, 18])
print(f"Mod variable: {int32_variable.numpy()}")

Old variable: [20 40 15]
Mod variable: [12 15 18]


We can not assign a tensor with a different shape from the existing variable!

In [109]:
try:
  int32_variable = int32_variable.assign([12, 15, 18, 20]) # tensor with different shape
except Exception as e:
  print(f"{type(e).__name__}: {e}")

ValueError: Cannot assign value to variable ' UnreadVariable': Shape mismatch.The variable shape (3,), and the assigned value shape (4,) are incompatible.


#### Updating variable values with `assign.add`

We can add a specific value to the current value of an existing variable with `tf.Variable.assign_add`. The method is particularly useful for implementing counters or variables that need to be incremented during the execution for instance counting training steps(As we shall see later).

In [110]:
example_variable2 = tf.Variable([10,30])
example_variable2 = example_variable2.assign_add([200, 100])
example_variable2.numpy()

array([210, 130], dtype=int32)

In [111]:
example_variable1 = tf.Variable(10)
example_variable2 = tf.Variable([10,30])
print(f"Current variable1 value: {example_variable1.numpy()}")
print(f"Current variable2 values: {example_variable2.numpy()}")

# increment values in the variables
example_variable1 = example_variable1.assign_add(5) # add 5 to current value
example_variable2 = example_variable2.assign_add([200, 100]) # add 200 & 100 to current values

print(f"Updated variable1 value: {example_variable1.numpy()}")
print(f"Updated variable2 values: {example_variable2.numpy()}")

Current variable1 value: 10
Current variable2 values: [10 30]
Updated variable1 value: 15
Updated variable2 values: [210 130]


You notice that we mentioned that one of the major use cases of variables is to store trainable parameters. They can also hold gradients computed during backpropagation on a neural network model. However,  not all variables(for instance counters or constant values) in a model need to be trainables or have gradients. They can just be part of the model but don't need to be updated through optimization.
We can specify whether or not a variable needs updating during the training process, or its gradients computed during backpropagation. We do this by setting the trainable parameter to False. For instance:

In [112]:
# set a non-trainable variable to count training steps
train_step = tf.Variable(initial_value=0, trainable=False)
train_step

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=0>

Example loop using the non-trainable variable

In [113]:
# SAMPLE MODEL HERE
...
# set a non-trainable variable to count training steps
train_step = tf.Variable(initial_value=0, trainable=False)

...

# Example training loop
for epoch in range(5):  # Run for 5 epochs
    for step in range(len(x_train)):
        # Forward pass
        with tf.GradientTape() as tape:
            pass

        # Perform backward pass and optimization here
        ...

        # Update the train step variable here
        train_step.assign_add(1)

    print(f"Epoch {epoch + 1}, train step: {train_step.numpy()}")

# Display the final training step value
print("Final Global Step:", train_step.numpy())


Epoch 1, train step: 100
Epoch 2, train step: 200
Epoch 3, train step: 300
Epoch 4, train step: 400
Epoch 5, train step: 500
Final Global Step: 500


### Creating tensors from NumPy Arrays

We can easily create tensors from NumPy arrays. We can use `tf.convert_to_tensor` method or call tf.constant function on the particular NumPy array

In [114]:
np_array = np.arange(0, 12).reshape(3, 4)
print(np_array, type(np_array))


# convert to tensor
np_array_to_tensor = tf.convert_to_tensor(np_array)
print()
print(np_array_to_tensor)

# Alternatively we can call tf.constant on the array
np_array_to_tensor = tf.constant(np_array, dtype='float32')
print()
print(np_array_to_tensor)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] <class 'numpy.ndarray'>

tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]], shape=(3, 4), dtype=int64)

tf.Tensor(
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]], shape=(3, 4), dtype=float32)


### Creating random tensors

* `tf.random.normal`
* `tf.random.uniform`
* `tf.random.truncated_normal`
* `tf.random.shuffle`
* `tf.random.set_seed`
* `tf.keras.initializers.RandomNormal`





#### `tf.random.normal`

The tf.random.normal function creates tensors with random values from a normal(Gaussian) distribution. A normal distribution depicts two parameters: a mean and a standard deviation. That means we can set the two parameters for the random tensor.

In [115]:
# generate a 3x2 tensor containing random values
# sampled from a normal distribution with a mean of 0.0
# and a standard deviation of 1.0
random_normal_tensor = tf.random.normal(shape=(3, 2),
                                        mean=0, stddev=1,
                                        dtype='float32')
print(random_normal_tensor)

tf.Tensor(
[[ 0.33875433  0.3449861 ]
 [-0.6605785  -0.2854994 ]
 [ 0.43852386  0.8288566 ]], shape=(3, 2), dtype=float32)


### Create a random tensor with `tf.random.uniform`

The `tf.random.uniform` function creates tensors with random values from a uniform distribution. A normal distribution is a probability distribution where all values in the range have an equal probability of being sampled. That means that every value in the specified interval has the same likelihood of being chosen. So, we can generate a random tensor with a set range(min_value, max_value).

In [116]:
# generate a 2x3x2 tensor containing random values
# sampled from a uniform distribution with a min_value of 0.0
# and a max_value of 1.5
random_uniform_tensor = tf.random.uniform(shape=[2, 3, 2],
                                          maxval=0,
                                          minval=1.5)
print(random_uniform_tensor)

tf.Tensor(
[[[0.7655597  0.62131155]
  [0.95322454 0.5174237 ]
  [0.13873744 0.9366349 ]]

 [[0.4676442  1.1192393 ]
  [0.75032634 0.73108864]
  [0.40813637 0.61936194]]], shape=(2, 3, 2), dtype=float32)


### How to shuffle tensors to introduce randomness

The `tf.random.shuffle` function in TensorFlow is used to randomly shuffle the elements along the first dimension of a tensor. For a 2D or rank 2 tensor, this means shuffling the rows.

In [117]:
intial_tensor_data = tf.constant([[10, 15], [20, 30], [40, 50]])
print("Original:")
print(intial_tensor_data.numpy())
# shuffle the elements
shuffled_intial_tensor_data = tf.random.shuffle(intial_tensor_data)
print("\nShuffled:")
print(shuffled_intial_tensor_data.numpy())

Original:
[[10 15]
 [20 30]
 [40 50]]

Shuffled:
[[10 15]
 [40 50]
 [20 30]]


### Random seeds for random tensor generation

TensorFlow has two ways we can set the random seed for random tensor generation:
* Global-level random seed setting
* Operation-level random seed setting

Global-level random seed...

We set the global seeds with `tf.random.set_seed(seed=integer_value)`. A global seed is shared for all TensorFlow operations in that notebook, which means that any random operation will be affected by it. Typically, we set the global seed at the beginning of your script or notebook.

In [118]:
# set the global random seed
tf.random.set_seed(42)

random_tensor = tf.random.uniform(shape=[1, 3, 2])

print(random_tensor)

tf.Tensor(
[[[0.6645621  0.44100678]
  [0.3528825  0.46448255]
  [0.03366041 0.68467236]]], shape=(1, 3, 2), dtype=float32)


reproducibility...

In [119]:
# set the global random seed
tf.random.set_seed(42)
random_tensor = tf.random.uniform(shape=[1, 3, 2])

print(random_tensor)

tf.Tensor(
[[[0.6645621  0.44100678]
  [0.3528825  0.46448255]
  [0.03366041 0.68467236]]], shape=(1, 3, 2), dtype=float32)


try change the seed value...changing the seed value results will be different for the same tensor

In [120]:
# set a different global random seed value
tf.random.set_seed(123)
random_tensor = tf.random.uniform(shape=[1, 3, 2],
                                          maxval=0,
                                          minval=1.5)

print(random_tensor)

tf.Tensor(
[[[1.3107703  0.6408731 ]
  [1.05103    0.6807246 ]
  [0.4192264  0.31657004]]], shape=(1, 3, 2), dtype=float32)


Operational level random seed...

Operational-level random seeds are currently the most recommended way to ensure the reproducibility of random tensors. We set the seed with `tf.random.Generator` class. Each random tensor generated with this class has its own random seed, thus unique randomness. This can be helpful when we want different parts of the code to have independent random sequences.

In [121]:
# Create two instances of tf.random.Generator
# with different seeds
random_generator1 = tf.random.Generator.from_seed(42)
random_generator2 = tf.random.Generator.from_seed(123)

# use the generators for random tensor generation
random_tensor1 = random_generator1.normal(shape=[4, 2])
random_tensor2 = random_generator1.uniform(shape=[1, 3, 3])

print(random_tensor1)
print(random_tensor2)

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]
 [ 0.09988727 -0.50998646]], shape=(4, 2), dtype=float32)
tf.Tensor(
[[[0.2674625  0.32031918 0.4377985 ]
  [0.57189393 0.65885174 0.11768913]
  [0.11456561 0.19414282 0.03774476]]], shape=(1, 3, 3), dtype=float32)


#### Ragged tensors
A ragged tensor is mainly used to represent sequences of variable lengths. While dense tensors have dimensions of fixed sizes, ragged tensors have some of their dimension sizes varying. They can be helpful in tasks like NLP, where there are sequences of sentences with different numbers of words.

`tf.ragged.constant()`

In [122]:
# sample array of varying dimension sizes
ragged_array = [
    [1.5, 3.0, 2.3],
    [4.5, 0.5],
    [0.8]]

# we can not convert it to a dense tensor
try:
  tensor = tf.constant(ragged_array)
except Exception as e:
  print(f"{type(e).__name__}: {e}")

# instead we can convert it to a ragged tensor
ragged_tensor = tf.ragged.constant(ragged_array)
print("\nConverted to ragged tensor:")
print(ragged_tensor)

ValueError: Can't convert non-rectangular Python sequence to Tensor.

Converted to ragged tensor:
<tf.RaggedTensor [[1.5, 3.0, 2.3], [4.5, 0.5], [0.8]]>


Ragged tensor encoding...

You notice that the ragged tensor is not presented like normal tensors. Instead, it is encoded such that its variable-length rows are concatenated into a flattened list. The flattened list has row partitions that indicate the row divisions:

#### Constructing a ragged tensor using <code>value_rowids</code> partitioning tensor

In [123]:
# tf.RaggedTensor.from_value_rowids

values = tf.constant([20, 30, 40, 50, 60, 70]) # must be a vector
row_ids = tf.constant([0, 0, 0, 1, 1, 2]) # integer vector specifying the row index for each value
print("Values:" ,values.numpy())
print("Row ids:" ,row_ids.numpy())

ragged_tensor = tf.RaggedTensor.from_value_rowids(values = values, value_rowids=row_ids)
print("Ragged tensor from value_row_ids:\n" , ragged_tensor)

Values: [20 30 40 50 60 70]
Row ids: [0 0 0 1 1 2]
Ragged tensor from value_row_ids:
 <tf.RaggedTensor [[20, 30, 40], [50, 60], [70]]>


Constructing a ragged tensor using `row_lengths` partitioning tensor


In [124]:
# tf.RaggedTensor.from_row_lengths
values = tf.constant([20, 30, 40, 50, 60, 70]) # must be a vector
row_lengths = tf.constant([3, 2, 1]) # integer vector specifying the length of each row

# ragged tensor
ragged_tensor2 = tf.RaggedTensor.from_row_lengths(values = values,
                                                  row_lengths = row_lengths)
print("Values:" ,values.numpy())
print("Row lengths:" ,row_lengths.numpy())
print("Ragged tensor from row lengths:\n" , ragged_tensor2)

Values: [20 30 40 50 60 70]
Row lengths: [3 2 1]
Ragged tensor from row lengths:
 <tf.RaggedTensor [[20, 30, 40], [50, 60], [70]]>


Constructing a ragged tensor using <code>row_splits</code> partitioning tensor

In [125]:
# tf.RaggedTensor.from_row_splits
values = tf.constant([20, 30, 40, 50, 60, 70]) # must be a vector
row_splits = tf.constant([0, 3, 5, 6]) # integer vector specifying
                                       # the split points between rows

ragged_tensor3 = tf.RaggedTensor.from_row_splits(values = values,
                                                  row_splits = row_splits)

print("Values:" ,values.numpy())
print("Row splits:" ,row_lengths.numpy())
print("Ragged tensor from row_splits:\n" , ragged_tensor3)

Values: [20 30 40 50 60 70]
Row splits: [3 2 1]
Ragged tensor from row_splits:
 <tf.RaggedTensor [[20, 30, 40], [50, 60], [70]]>


In [126]:
# shape of the ragged_tensor3 above
print(ragged_tensor3.shape) # static shape

print(tf.shape(ragged_tensor3)) # dynamic shape

(3, None)
<DynamicRaggedShape lengths=[3, (3, 2, 1)] num_row_partitions=1>


### Sparse Tensors

In [127]:
# indices of non-zero values
indices = tf.constant([[0, 1], [1, 2], [2, 0]], dtype=tf.int64)
# the nonzero values in the tensor
values = tf.constant([15, 25, 35], dtype=tf.float32)
# define the tensor's shape
shape = tf.constant([4,3], dtype=tf.int64)

sparse_tensor = tf.sparse.SparseTensor(indices = indices,
                                       values = values,
                                       dense_shape= shape)
print(sparse_tensor)

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 2]
 [2 0]], shape=(3, 2), dtype=int64), values=tf.Tensor([15. 25. 35.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([4 3], shape=(2,), dtype=int64))


In [128]:
# convert sparse tensor to dense tensor
sparse_to_dense_tensor = tf.sparse.to_dense(sparse_tensor)
print(sparse_to_dense_tensor)

tf.Tensor(
[[ 0. 15.  0.]
 [ 0.  0. 25.]
 [35.  0.  0.]
 [ 0.  0.  0.]], shape=(4, 3), dtype=float32)


## Operations with tensors

Indexing tensors follows the basic Python and NumPy indexing rules, which include:
* Indexes start at 0
* Negative indices count backward from the end.
* Colons, :, are used for slices: `start:stop:step`

In [129]:
tensor = tf.constant([20, 30, 40, 50, 15, 45, 100, 120])
print(f"Tensor: {tensor.numpy()}")

# return everything
print(f"Return everything: {tensor[:]}")
print(f"First 3 elements: {tensor[:3]}")
print(f"All elements after first 3 elements: {tensor[3:]}")
print(f"Every other item: {tensor[::2]}")
print(f"Elements between fourth and before 7th element: {tensor[3:6]}")
print(f"Reversing: {tensor[::-1]}")

Tensor: [ 20  30  40  50  15  45 100 120]
Return everything: [ 20  30  40  50  15  45 100 120]
First 3 elements: [20 30 40]
All elements after first 3 elements: [ 50  15  45 100 120]
Every other item: [ 20  40  15 100]
Elements between fourth and before 7th element: [50 15 45]
Reversing: [120 100  45  15  50  40  30  20]


In [130]:
rank_2tensor = tf.constant([[20, 30, 40], [50, 15, 45], [100, 120, 150]])
print(f"Tensor:\n{rank_2tensor.numpy()}")

print(f"Second row:, {rank_2tensor[1, :].numpy()}")
print(f"Second column:, {rank_2tensor[:, 1].numpy()}")
print(f"Last row:, {rank_2tensor[-1, :].numpy()}")
print(f"First item in last column:, {rank_2tensor[0, -1].numpy()}")
print(f"Second row onwards:\n {rank_2tensor[1:, :].numpy()}")

Tensor:
[[ 20  30  40]
 [ 50  15  45]
 [100 120 150]]
Second row:, [50 15 45]
Second column:, [ 30  15 120]
Last row:, [100 120 150]
First item in last column:, 40
Second row onwards:
 [[ 50  15  45]
 [100 120 150]]


Using `tf.slice`

`tf.slice` takes begin and size parameters. begin specifies the start index for the slicing, while thesizespecifies the number of elements to slice.

In [131]:
tensor = tf.constant([20, 30, 40, 50, 15, 25, 60])
print(f"Tensor:\n{rank_2tensor.numpy()}")

# slice with tf.slice
begin = [2] # begin at index 2
size = [3] # number of elements to slice starting from begin index
t_slice = tf.slice(tensor, begin = begin, size=size)
print(f"\nSlice: {t_slice.numpy()}") # similar to tensor[2:5]

Tensor:
[[ 20  30  40]
 [ 50  15  45]
 [100 120 150]]

Slice: [40 50 15]


In [132]:
r3_tensor = tf.constant([
    [[20, 30, 40, 15],
     [50, 15, 25, 60]],
    [[5, 16, 21, 17],
     [9, 11, 35, 13]]])

r3_slice = tf.slice(r3_tensor, begin=[1, 1, 1], size=[1, 1, 2])
print(f"Tensor: \n{r3_tensor.numpy()}")
print(f"\nr3_slice: {r3_slice.numpy()}")

Tensor: 
[[[20 30 40 15]
  [50 15 25 60]]

 [[ 5 16 21 17]
  [ 9 11 35 13]]]

r3_slice: [[[11 35]]]


Using `tf.gather`

`tf.gather` extracts specific indices from a single axis/dimension of a tensor. The indices must be an integer tensor of any dimension but primarily 1D.

In [133]:
print(f"r1_tTensor: {tensor.numpy()}")
print(f"Gathered:\n {tf.gather(tensor, indices=[1, 5])}") # take index 1 and 5

r1_tTensor: [20 30 40 50 15 25 60]
Gathered:
 [30 25]


In [134]:
print(f"r2_tensor: \n{rank_2tensor}")
print("Gathered:")
print(tf.gather(rank_2tensor, indices=[0, 2], axis=1).numpy())

r2_tensor: 
[[ 20  30  40]
 [ 50  15  45]
 [100 120 150]]
Gathered:
[[ 20  40]
 [ 50  45]
 [100 150]]


In [135]:
tensor_2d = tf.constant([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]])
indices = tf.constant([
    [2, 4],
    [0, 4],
    [1, 3]])
print(tensor_2d.numpy())
print()
print(tf.gather(tensor_2d, indices=indices, batch_dims=1).numpy())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

[[ 3  5]
 [ 6 10]
 [12 14]]


## Operations for reshaping and manipulating tensors:
* `tf.reshape`
* `tf.squeeze`
* `tf.split`
* `tf.expand_dims`
* `tf.transpose`
* `tf.concat`

#### Reshaping...

`tf.reshape` enables us to reshape a tensor without altering its data(only the shape is changed!).

In [136]:
tensor = tf.constant([[1, 2, 3, 4],
                      [5, 6, 7, 8]])
print(f"Tensor:\n{tensor.numpy()} \nOld shape: {tensor.shape}")

# reshape
tensor = tf.reshape(tensor, [2, 2, 2])
print(f"Reshaped:\n{tensor.numpy()} \nNew shape: {tensor.shape}")

Tensor:
[[1 2 3 4]
 [5 6 7 8]] 
Old shape: (2, 4)
Reshaped:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 
New shape: (2, 2, 2)


In [137]:
var_tensor = tf.Variable([[[1, 2, 3, 4],
                        [5, 6, 7, 8]],
                       [[9, 10, 11, 12],
                        [13, 14, 15, 16]]])
print(f"Tensor:\n{var_tensor.numpy()} \nOld shape: {var_tensor.shape}")

# reshape
var_tensor = tf.reshape(var_tensor, [4, 4])
print(f"Reshaped:\n{var_tensor.numpy()} \nNew shape: {var_tensor.shape}")


Tensor:
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 
Old shape: (2, 2, 4)
Reshaped:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 
New shape: (4, 4)


Flatten the tensor into a 1D(rank 1) tensor

In [138]:
# flatten the variable tensor
print(f"Tensor:\n{var_tensor.numpy()}")

var_tensor = tf.reshape(var_tensor, [-1])
print(f"Flattened:\n{var_tensor.numpy()} \nNew shape: {var_tensor.shape}")

Tensor:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Flattened:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16] 
New shape: (16,)


#### Transposing...`tf.transpose`

Transposing a tensor means switching its rows and columns. For instance, in a rank 2 tensor, that means swapping its rows and columns

In [139]:
var_tensor = tf.reshape(var_tensor, [2, 2, 4])
print(f"Tensor:\n{var_tensor.numpy()} shape before: {tf.shape(var_tensor)}")

# transpose
var_tensor = tf.transpose(var_tensor, perm=[0, 2, 1]) # row => columns, columns => rows
print(f"Transposed:\n{var_tensor.numpy()}\
      shape after: {tf.shape(var_tensor)}")

Tensor:
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] shape before: [2 2 4]
Transposed:
[[[ 1  5]
  [ 2  6]
  [ 3  7]
  [ 4  8]]

 [[ 9 13]
  [10 14]
  [11 15]
  [12 16]]]      shape after: [2 4 2]


In [140]:
# Create a tensor representing a single image with batch dimension
image_with_batch = tf.constant([[[[1, 2, 3], [4, 5, 6]]]])

# Squeeze batch dimension
image_without_batch = tf.squeeze(image_with_batch, axis=0)

print("Original Image with Batch Dimension:")
print(image_with_batch)
print("Image without Batch Dimension:")
print(image_without_batch)

Original Image with Batch Dimension:
tf.Tensor(
[[[[1 2 3]
   [4 5 6]]]], shape=(1, 1, 2, 3), dtype=int32)
Image without Batch Dimension:
tf.Tensor(
[[[1 2 3]
  [4 5 6]]], shape=(1, 2, 3), dtype=int32)


#### Squeezing tensors(removing dimensions of size 1) ... `tf.squeeze`

Squeezing does not change the data in the tensor but only modifies its shape.

In [141]:
tensor = tf.constant([[[10], [15], [30]]])
print(f"Tensor:\n{tensor} => shape: {tf.shape(tensor)}")

# squeeze
tensor = tf.squeeze(tensor)
print("\nSqueezed:")
print(f"{tensor.numpy()} => New shape: {tf.shape(tensor)}")

Tensor:
[[[10]
  [15]
  [30]]] => shape: [1 3 1]

Squeezed:
[10 15 30] => New shape: [3]


In [142]:
tensor2 = tf.constant([[[[1, 2, 3, 4],
                        [5, 6, 7, 8]],
                       [[9, 10, 11, 13],
                        [14, 15, 16, 17]]]])

print(f"Tensor:\n{tensor2} => shape: {tf.shape(tensor2)}")

# squeeze
tensor2 = tf.squeeze(tensor2, axis=[0])
print(f"\nSqueezed:\n {tensor2.numpy()} => New shape: {tf.shape(tensor2)}")

Tensor:
[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 13]
   [14 15 16 17]]]] => shape: [1 2 2 4]

Squeezed:
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 13]
  [14 15 16 17]]] => New shape: [2 2 4]


In [143]:
tensor3 = tf.constant([[[10]],
                       [[11]],
                       [[9]]])
print(f"Tensor:\n{tensor3} => shape: {tf.shape(tensor3)}")

# specify the axis(squeeze axis 2)
tensor3 = tf.squeeze(tensor3, axis=[2])
print("\nSqueezed:")
print(f"{tensor3.numpy()} => New shape: {tf.shape(tensor3)}")

Tensor:
[[[10]]

 [[11]]

 [[ 9]]] => shape: [3 1 1]

Squeezed:
[[10]
 [11]
 [ 9]] => New shape: [3 1]


In [144]:
tensor_with_singleton_dim = tf.constant([[[1], [2], [3]]])
tf.squeeze(tensor_with_singleton_dim).numpy()

array([1, 2, 3], dtype=int32)

In [145]:
ragged = tf.ragged.constant([[[20],
                              [16, 18],
                              [9, 1, 3, 6, 11]]])

tf.squeeze(ragged, axis=[0])

<tf.RaggedTensor [[20], [16, 18], [9, 1, 3, 6, 11]]>

#### How to add dimensions to tensors(adding dimensions of size 1) with `tf.expand_dims`


In [146]:
tensor = tf.constant([10, 20, 30])
print(f"Tensor:\n{tensor} => shape: {tf.shape(tensor)}")

# expand dimensions
tensor_expanded = tf.expand_dims(tensor, axis = [0])
print("Tensor expanded:")
print(f"{tensor_expanded} => shape: {tf.shape(tensor_expanded)}")

Tensor:
[10 20 30] => shape: [3]
Tensor expanded:
[[10 20 30]] => shape: [1 3]


In [147]:
tensor_expanded = tf.expand_dims(tensor, axis = [-1]) # innermost ndim
print("Tensor expanded(axis=-1):")
print(f"{tensor_expanded} => shape: {tf.shape(tensor_expanded)}")

Tensor expanded(axis=-1):
[[10]
 [20]
 [30]] => shape: [3 1]


### How to concatenate tensors with `tf.concat` along a specific axis

In [148]:
tensor_1 = tf.constant([[1, 2, 3],
                        [4, 5, 6]])
tensor_2 = tf.constant([[7, 8, 9],
                        [10, 11, 12]])
print(f"Tensor 1:\n{tensor_1}")
print(f"Tensor 2:\n{tensor_2}")

# concatenate along axis=0
tensor1_tensor2 = tf.concat([tensor_1, tensor_2], axis=[0])
print("tensor_1 and tensor_2 joined(axis=0):")
print(f"{tensor1_tensor2} => shape: {tf.shape(tensor1_tensor2)}")

Tensor 1:
[[1 2 3]
 [4 5 6]]
Tensor 2:
[[ 7  8  9]
 [10 11 12]]
tensor_1 and tensor_2 joined(axis=0):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] => shape: [4 3]


In [149]:
# concatenate along axis=1
tensor1_tensor2 = tf.concat([tensor_1, tensor_2], axis=[1])
print("tensor_1 and tensor_2 joined(axis=1):")
print(f"{tensor1_tensor2} => shape: {tf.shape(tensor1_tensor2)}")

tensor_1 and tensor_2 joined(axis=1):
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]] => shape: [2 6]


## Broadcasting tensors

In [150]:
tensor = tf.constant([5, 10, 15])

#multiply by scalar 5
print(tf.multiply(tensor, 5))


tf.Tensor([25 50 75], shape=(3,), dtype=int32)


Broadcasting rules:

* Rule 1: If the two tensors vary in their number of dimensions, the shape of the one with lesser dimensions is padded with ones on its left side.
* Rule 2: If the shape of the two tensors does not match in any dimension, the tensor with a shape of 1 in that dimension is stretched to match the other shape.
* Rule 3: If, in any dimension, the sizes differ and neither is 1, an error is raised.

In [151]:
rank1_t = tf.constant([1, 2 , 3])
rank2_t = tf.constant([[5, 10, 15],
                       [20, 25, 30]])


# shapes
print(f"rank1_t shape: {rank1_t.shape}")
print(f"rank2_t shape: {rank2_t.shape}")

# add
r2_plus_r1 = rank1_t + rank2_t
print("r2_plus_r1:")
print(f"{r2_plus_r1} => shape{r2_plus_r1.shape}")

rank1_t shape: (3,)
rank2_t shape: (2, 3)
r2_plus_r1:
[[ 6 12 18]
 [21 27 33]] => shape(2, 3)


In [152]:
t1 = tf.constant([1, 2 , 3, 4])
t2 = tf.constant([[10],
                  [20],
                  [30],
                  [40]])
# shapes
print(f"t1 shape: {t1.shape}")
print(f"t2 shape: {t2.shape}")

# multiply
t2_x_t1 = t2 + t1
print("t2_x_t1:")
print(f"{t2_x_t1} => shape{t2_x_t1.shape}")

t1 shape: (4,)
t2 shape: (4, 1)
t2_x_t1:
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]] => shape(4, 4)


## Basic mathematical operations with tensors

In [153]:
# Example tensors
tensor_a = tf.constant([[1, 2], [3, 4]])
tensor_b = tf.constant([[5, 6], [7, 8]])

print("Tensor A:")
print(tensor_a)
print("Tensor B:")
print(tensor_b)


Tensor A:
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Tensor B:
tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


In [154]:
# Addition
result_addition = tensor_a + tensor_b
print("Addition Result:")
print(result_addition.numpy())

Addition Result:
[[ 6  8]
 [10 12]]


In [155]:
# Subtraction
result_subtraction = tensor_a - tensor_b

print("Subtraction Result:")
print(result_subtraction.numpy())

Subtraction Result:
[[-4 -4]
 [-4 -4]]


In [156]:
# Element-wise multiplication
result_elementwise_multiplication = tf.multiply(tensor_a, tensor_b)

# Matrix multiplication
result_matrix_multiplication = tf.matmul(tensor_a, tensor_b)

print("Element-wise Multiplication Result:")
print(result_elementwise_multiplication.numpy())
print("Matrix Multiplication Result:")
print(result_matrix_multiplication.numpy())

Element-wise Multiplication Result:
[[ 5 12]
 [21 32]]
Matrix Multiplication Result:
[[19 22]
 [43 50]]


In [157]:
# Element-wise division
result_elementwise_division = tf.divide(tensor_a, tensor_b)

print("Element-wise Division Result:")
print(result_elementwise_division.numpy())

Element-wise Division Result:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [158]:
# Define matrices A and B
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])

# Matrix multiplication with tf.matmul
C = tf.matmul(A, B)

print("Matrix A:")
print(A.numpy())
print("Matrix B:")
print(B.numpy())
print("Matrix Multiplication Result (C):")
print(C.numpy())

Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
Matrix Multiplication Result (C):
[[19 22]
 [43 50]]


## Tensor aggregation functions

* `tf.reduce_sum`
* `tf.reduce_min and tf.reduce max`
* `tf.reduce_mean`
* `tf.argmax and tf.argmin`


In [159]:
example_t = tf.constant([[5, 10, 15],
                        [20, 25, 30]])

print(example_t.numpy())

[[ 5 10 15]
 [20 25 30]]


`tf.reduce_sum`

In [160]:
sum_of_all_elems = tf.reduce_sum(example_t)
sum_axis_0 = tf.reduce_sum(example_t, axis = 0)
sum_axis_1 = tf.reduce_sum(example_t, axis = 1)

print(f"Tensor: \n{example_t.numpy()}")
print("Sum of all elements:", sum_of_all_elems.numpy())
print("Sum on axis 0:", sum_axis_0.numpy())
print("Sum on axis 1:", sum_axis_1.numpy())


Tensor: 
[[ 5 10 15]
 [20 25 30]]
Sum of all elements: 105
Sum on axis 0: [25 35 45]
Sum on axis 1: [30 75]


`tf.reduce_mean`

In [161]:
tensor_mean = tf.reduce_mean(example_t)
mean_axis_0 = tf.reduce_mean(example_t, axis = 0)
mean_axis_1 = tf.reduce_mean(example_t, axis = 1)

print(f"Tensor: \n{example_t.numpy()}")
print("Mean of all elements:", tensor_mean.numpy())
print("Mean on axis 0:", mean_axis_0.numpy())
print("Mean on axis 1:", mean_axis_1.numpy())

Tensor: 
[[ 5 10 15]
 [20 25 30]]
Mean of all elements: 17
Mean on axis 0: [12 17 22]
Mean on axis 1: [10 25]


`tf.reduce_min` and `tf.reduce_max`

In [162]:
# Along axis 0
max_axis_0 = tf.reduce_max(example_t, axis=0)
min_axis_0 = tf.reduce_min(example_t, axis=0)

# Along axis 1
max_axis_1 = tf.reduce_max(example_t, axis=1)
min_axis_1 = tf.reduce_min(example_t, axis=1)

print(f"Tensor: \n{example_t.numpy()}")
print("Max axis 0:", max_axis_0.numpy())
print("Min axis 0:", min_axis_0.numpy())
print("Max axis 1:", max_axis_1.numpy())
print("Min axis 1:", min_axis_1.numpy())


Tensor: 
[[ 5 10 15]
 [20 25 30]]
Max axis 0: [20 25 30]
Min axis 0: [ 5 10 15]
Max axis 1: [15 30]
Min axis 1: [ 5 20]


`tf.argmax` and `tf.argmin`

In [163]:
# Along axis 0
argmax_axis_0 = tf.argmax(example_t, axis=0)
argmin_axis_0 = tf.argmin(example_t, axis=0)

# Along axis 1
argmax_axis_1 = tf.argmax(example_t, axis=1)
argmin_axis_1 = tf.argmin(example_t, axis=1)

print(f"Tensor: \n{example_t.numpy()}")
print("Index of max value axis 0:", argmax_axis_0.numpy())
print("Index of min value axis 0:", argmin_axis_0.numpy())
print("Index of max value axis 1:", argmax_axis_1.numpy())
print("Index of min value axis 1:", argmin_axis_1.numpy())

Tensor: 
[[ 5 10 15]
 [20 25 30]]
Index of max value axis 0: [1 1 1]
Index of min value axis 0: [0 0 0]
Index of max value axis 1: [2 2]
Index of min value axis 1: [0 0]
